# Generated by Django 3.1 on 2020-12-10 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=2000)),
                ('starting_bid', models.IntegerField()),
                ('image', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
